//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassLists = new HashSet<ClassList>();
            this.ATTENDANCEs = new HashSet<ATTENDANCE>();
        }
    
        public int id { get; set; }
        public string ClassCode { get; set; }
        public string LessonCode { get; set; }
        public string ClassName { get; set; }
        public string Credit { get; set; }
        public string LessonType { get; set; }
        public Nullable<int> DayLearn { get; set; }
        public string ClassTime { get; set; }
        public string Room { get; set; }
        public Nullable<int> TotalStudent { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TotalWeek { get; set; }
        public string Scholastic { get; set; }
        public Nullable<int> Semesterid { get; set; }
        public string Userid { get; set; }
        public Nullable<int> Facultyid { get; set; }
        public Nullable<int> NoSession { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual FACULTY FACULTY { get; set; }
        public virtual SEMESTER SEMESTER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassList> ClassLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTENDANCE> ATTENDANCEs { get; set; }
    }
}
